export const ADD_REPETITION = "ADD_REPETITION";
export const REMOVE_REPETITION = "REMOVE_REPETITION";
export const INCREASE_REPETITION_ID = "INCREASE_REPETITION_ID";
export const GET_EMPTY_REPETITION_WITH_ID = "GET_EMPTY_REPETITION_WITH_ID";
